import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

export type Lang = 'uk' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  uk: {
    // Auth
    'auth.title': 'LifeSync',
    'auth.subtitle': 'Ваш інтелектуальний life & task manager',
    'auth.login': 'Вхід в систему',
    'auth.loginLabel': 'Логін',
    'auth.loginPlaceholder': 'Введіть логін',
    'auth.passwordLabel': 'Пароль',
    'auth.passwordPlaceholder': 'Введіть пароль',
    'auth.submit': 'Увійти',
    'auth.loading': 'Вхід…',
    'auth.error': 'Невірний логін або пароль',
    'auth.calendar': 'Календар',
    'auth.finance': 'Фінанси',
    'auth.ai': 'AI Асистент',
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Календар',
    'nav.tasks': 'Задачі',
    'nav.finance': 'Фінанси',
    'nav.ai': 'AI-Асистент',
    'nav.projectName': 'Проєкт Life Manager',
    'sidebar.googleWorkspace': 'Google Workspace',
    'sidebar.synced': 'Синхронізовано',
    'sidebar.saving': 'Збереження…',
    'sidebar.offline': 'Офлайн',
    'sidebar.settings': 'Налаштування',
    // Header
    'header.search': 'Пошук…',
    'header.searchHint': 'Почніть вводити для пошуку…',
    // Dashboard
    'dash.tasks': 'Задачі',
    'dash.calendarEvents': 'Календарні події',
    'dash.addTask': 'Додати задачу',
    'dash.addEvent': 'Додати подію',
    'dash.importantDocs': '📌 Важливі документи',
    'dash.fromTasks': 'з задач',
    'dash.addDoc': '+ Додати',
    'dash.quickInput': '⚡ Швидке введення',
    'dash.quickPlaceholder': 'Введіть задачу, подію або транзакцію…',
    'dash.saveTemplate': 'Зберегти шаблон',
    'dash.attach': 'Прикріпити',
    'dash.emoji': 'Емодзі',
    'dash.attachFile': 'Прикріпити файл',
    'dash.tags': 'Теги',
    'dash.tagTask': '📋 Задача',
    'dash.tagEvent': '📅 Подія',
    'dash.tagExpense': '💸 Витрата',
    'dash.finOverview': '💰 Фінансовий огляд',
    'dash.finSummary': 'Фінансовий огляд',
    'dash.income': 'Дохід',
    'dash.expense': 'Витрата',
    'dash.addTransaction': '+ Транзакція',
    'dash.txName': 'Назва',
    'dash.txAmount': 'Сума',
    'dash.txCategory': 'Категорія',
    'dash.txType': 'Тип',
    'dash.txAdd': 'Додати',
    'dash.txCancel': 'Скасувати',
    'dash.noTasks': 'Немає задач на сьогодні',
    'dash.noEvents': 'Немає подій',
    'dash.noDocs': 'Немає документів',
    'dash.newTask': 'Нова задача',
    'dash.edit': 'Редагувати',
    'dash.delete': 'Видалити',
    'dash.unpin': 'Відкріпити',
    'dash.pin': 'Закріпити',
    // Tasks & Habits
    'tasks.title': '✅ Таск-менеджер',
    'tasks.all': 'Всі',
    'tasks.high': '🔴 Високий',
    'tasks.medium': '🟡 Середній',
    'tasks.low': '🟢 Низький',
    'tasks.list': '≡ Список',
    'tasks.kanban': '⊞ Канбан',
    'tasks.addTask': '+ Задача',
    'tasks.taskName': 'Назва задачі…',
    'tasks.tag': 'Тег',
    'tasks.add': '✓ Додати',
    'tasks.noTasks': 'Немає задач',
    'tasks.open': 'Відкриті',
    'tasks.inProgress': 'В роботі',
    'tasks.done': 'Готово',
    'habits.title': '🔥 Трекер звичок',
    'habits.addHabit': '+ Звичка',
    'habits.habitName': 'Назва звички…',
    'habits.days': 'д',
    'habits.completed': 'Виконано',
    'habits.noHabits': 'Додайте першу звичку',
    'habits.done': 'Виконано',
    'habits.missed': 'Пропущено',
    'habits.deleteHabit': 'Видалити звичку',
    // Finance
    'fin.balance': 'Баланс',
    'fin.incomeLabel': 'Доходи',
    'fin.expenseLabel': 'Витрати',
    'fin.dynamics': '📈 Динаміка потоків',
    'fin.week': 'тиждень',
    'fin.month': 'місяць',
    'fin.categories': '📊 Категорії & Бюджети',
    'fin.budget': 'Бюджет',
    'fin.transactions': '📋 Транзакції',
    'fin.addTx': '+ Додати',
    'fin.filterAll': 'Всі',
    'fin.filterIncome': 'Доходи',
    'fin.filterExpense': 'Витрати',
    'fin.noTx': 'Немає транзакцій',
    'fin.txNote': 'Опис',
    'fin.txDate': 'Дата',
    'fin.customRate': 'Свій курс',
    'fin.rate': 'Курс',
    'fin.mon': 'Пн',
    'fin.tue': 'Вт',
    'fin.wed': 'Ср',
    'fin.thu': 'Чт',
    'fin.fri': 'Пт',
    'fin.sat': 'Сб',
    'fin.sun': 'Нд',
    // Calendar
    'cal.month': 'Місяць',
    'cal.week': 'Тиждень',
    'cal.day': 'День',
    'cal.today': 'Сьогодні',
    'cal.addEvent': '+ Подія',
    'cal.eventTitle': 'Назва події',
    'cal.eventDate': 'Дата',
    'cal.startTime': 'Початок',
    'cal.endTime': 'Кінець',
    'cal.location': 'Місце',
    'cal.color': 'Колір',
    'cal.save': 'Зберегти',
    'cal.cancel': 'Скасувати',
    'cal.delete': 'Видалити',
    'cal.noEvents': 'Немає подій',
    // AI
    'ai.title': '✦ AI-Асистент',
    'ai.greeting': 'Привіт',
    'ai.greetingText': 'Я LifeSync AI — ваш персональний асистент. Я можу допомогти з плануванням, аналізом фінансів та оптимізацією розкладу. Що бажаєте?',
    'ai.placeholder': 'Напишіть повідомлення…',
    'ai.send': 'Надіслати',
    'ai.suggestions': 'Швидкі дії',
    'ai.q1': 'Скільки я витратив цього тижня?',
    'ai.q2': 'Які пріоритетні задачі горять до завтра?',
    'ai.q3': 'Оптимізуй мій розклад на сьогодні',
    'ai.q4': 'Покажи звіт по звичках за місяць',
    'ai.insights': '📊 AI Insights',
    'ai.startAdding': 'Почніть додавати дані',
    'ai.insightsHint': 'AI аналітика стане доступна після заповнення задач та фінансів',
    // Settings
    'set.title': '⚙️ Налаштування',
    'set.profile': 'Профіль',
    'set.appearance': 'Зовнішній вигляд',
    'set.currencies': 'Валюти',
    'set.integrations': 'Інтеграції',
    'set.account': 'Акаунт',
    'set.language': 'Мова інтерфейсу',
    'set.nickname': "Ім'я / Нікнейм",
    'set.nickPlaceholder': "Введіть ваше ім'я",
    'set.email': 'Email облікового запису',
    'set.authMethod': 'Спосіб авторизації',
    'set.baseCurrency': 'Базова валюта інтерфейсу',
    'set.theme': 'Тема',
    'set.dark': '🌙 Темна',
    'set.light': '☀️ Світла',
    'set.accent': 'Акцентний колір',
    'set.rateInfo': 'Курс до UAH для автоматичного конвертування транзакцій у розділі «Фінанси».',
    'set.monobank': 'Monobank API',
    'set.monoDesc': 'Автоматичний імпорт транзакцій',
    'set.monoToken': 'API Token',
    'set.monoPlaceholder': 'Вставте токен з api.monobank.ua',
    'set.monoTest': 'Тест',
    'set.monoGetToken': 'Отримати персональний токен →',
    'set.connected': '● Підключено',
    'set.notConnected': '○ Не підключено',
    'set.google': 'Google Workspace',
    'set.googleDesc': 'Calendar · Drive · Docs · Gmail',
    'set.googleClientId': 'Google OAuth 2.0 Web Client ID',
    'set.googleConnect': 'Підключити Google',
    'set.googleUpdate': '✓ Підключено (Оновити)',
    'set.googleNeedAuth': 'Необхідна авторизація',
    'set.googleSynced': 'Акаунт синхронізовано',
    'set.changePassword': 'Змінити пароль',
    'set.exportData': 'Експортувати дані (JSON)',
    'set.logout': 'Вийти з акаунта',
    'set.deleteAccount': 'Видалити акаунт та очистити сховище',
    'set.deleteConfirm': 'Ви впевнені, що бажаєте видалити свій акаунт та всі пов\'язані дані? Цю дію неможливо скасувати.',
    'set.save': 'Зберегти',
    'set.saved': '✓ Збережено',
    'set.cancel': 'Скасувати',
    'set.syncStatus': 'Статус синхронізації',
    'set.newPassword': 'Новий пароль',
    'set.confirmPassword': 'Повторіть пароль',
    'set.savePassword': 'Зберегти пароль',
    'set.passwordTitle': 'Зміна пароля',
    'set.emailPassword': 'Email & Пароль',
    // TaskEditModal
    'edit.title': '✏️ Редагувати задачу',
    'edit.taskName': 'Назва задачі',
    'edit.taskPlaceholder': 'Назва задачі…',
    'edit.priority': 'Пріоритет',
    'edit.high': 'Високий',
    'edit.medium': 'Середній',
    'edit.low': 'Низький',
    'edit.tagCategory': 'Тег / Категорія',
    'edit.tagPlaceholder': 'Dev, Бізнес…',
    'edit.deadline': 'Дедлайн',
    'edit.status': 'Статус',
    'edit.open': '○ Відкрита',
    'edit.completed': '✓ Виконана',
    'edit.delete': '🗑 Видалити',
    'edit.cancel': 'Скасувати',
    'edit.save': 'Зберегти',
    // Common
    'common.close': 'Закрити',
    'common.more': 'Більше',
  },
  en: {
    // Auth
    'auth.title': 'LifeSync',
    'auth.subtitle': 'Your intelligent life & task manager',
    'auth.login': 'Sign In',
    'auth.loginLabel': 'Login',
    'auth.loginPlaceholder': 'Enter login',
    'auth.passwordLabel': 'Password',
    'auth.passwordPlaceholder': 'Enter password',
    'auth.submit': 'Sign In',
    'auth.loading': 'Signing in…',
    'auth.error': 'Invalid login or password',
    'auth.calendar': 'Calendar',
    'auth.finance': 'Finance',
    'auth.ai': 'AI Assistant',
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendar',
    'nav.tasks': 'Tasks',
    'nav.finance': 'Finance',
    'nav.ai': 'AI Assistant',
    'nav.projectName': 'Life Manager Project',
    'sidebar.googleWorkspace': 'Google Workspace',
    'sidebar.synced': 'Synced',
    'sidebar.saving': 'Saving…',
    'sidebar.offline': 'Offline',
    'sidebar.settings': 'Settings',
    // Header
    'header.search': 'Search…',
    'header.searchHint': 'Start typing to search…',
    // Dashboard
    'dash.tasks': 'Tasks',
    'dash.calendarEvents': 'Calendar Events',
    'dash.addTask': 'Add task',
    'dash.addEvent': 'Add event',
    'dash.importantDocs': '📌 Important Documents',
    'dash.fromTasks': 'from tasks',
    'dash.addDoc': '+ Add',
    'dash.quickInput': '⚡ Quick Input',
    'dash.quickPlaceholder': 'Type a task, event, or transaction…',
    'dash.saveTemplate': 'Save template',
    'dash.attach': 'Attach',
    'dash.emoji': 'Emoji',
    'dash.attachFile': 'Attach file',
    'dash.tags': 'Tags',
    'dash.tagTask': '📋 Task',
    'dash.tagEvent': '📅 Event',
    'dash.tagExpense': '💸 Expense',
    'dash.finOverview': '💰 Financial Overview',
    'dash.finSummary': 'Financial overview',
    'dash.income': 'Income',
    'dash.expense': 'Expense',
    'dash.addTransaction': '+ Transaction',
    'dash.txName': 'Name',
    'dash.txAmount': 'Amount',
    'dash.txCategory': 'Category',
    'dash.txType': 'Type',
    'dash.txAdd': 'Add',
    'dash.txCancel': 'Cancel',
    'dash.noTasks': 'No tasks for today',
    'dash.noEvents': 'No events',
    'dash.noDocs': 'No documents',
    'dash.newTask': 'New task',
    'dash.edit': 'Edit',
    'dash.delete': 'Delete',
    'dash.unpin': 'Unpin',
    'dash.pin': 'Pin',
    // Tasks & Habits
    'tasks.title': '✅ Task Manager',
    'tasks.all': 'All',
    'tasks.high': '🔴 High',
    'tasks.medium': '🟡 Medium',
    'tasks.low': '🟢 Low',
    'tasks.list': '≡ List',
    'tasks.kanban': '⊞ Kanban',
    'tasks.addTask': '+ Task',
    'tasks.taskName': 'Task name…',
    'tasks.tag': 'Tag',
    'tasks.add': '✓ Add',
    'tasks.noTasks': 'No tasks',
    'tasks.open': 'Open',
    'tasks.inProgress': 'In Progress',
    'tasks.done': 'Done',
    'habits.title': '🔥 Habit Tracker',
    'habits.addHabit': '+ Habit',
    'habits.habitName': 'Habit name…',
    'habits.days': 'd',
    'habits.completed': 'Completed',
    'habits.noHabits': 'Add your first habit',
    'habits.done': 'Done',
    'habits.missed': 'Missed',
    'habits.deleteHabit': 'Delete habit',
    // Finance
    'fin.balance': 'Balance',
    'fin.incomeLabel': 'Income',
    'fin.expenseLabel': 'Expenses',
    'fin.dynamics': '📈 Cash Flow Dynamics',
    'fin.week': 'week',
    'fin.month': 'month',
    'fin.categories': '📊 Categories & Budgets',
    'fin.budget': 'Budget',
    'fin.transactions': '📋 Transactions',
    'fin.addTx': '+ Add',
    'fin.filterAll': 'All',
    'fin.filterIncome': 'Income',
    'fin.filterExpense': 'Expenses',
    'fin.noTx': 'No transactions',
    'fin.txNote': 'Description',
    'fin.txDate': 'Date',
    'fin.customRate': 'Custom rate',
    'fin.rate': 'Rate',
    'fin.mon': 'Mon',
    'fin.tue': 'Tue',
    'fin.wed': 'Wed',
    'fin.thu': 'Thu',
    'fin.fri': 'Fri',
    'fin.sat': 'Sat',
    'fin.sun': 'Sun',
    // Calendar
    'cal.month': 'Month',
    'cal.week': 'Week',
    'cal.day': 'Day',
    'cal.today': 'Today',
    'cal.addEvent': '+ Event',
    'cal.eventTitle': 'Event name',
    'cal.eventDate': 'Date',
    'cal.startTime': 'Start',
    'cal.endTime': 'End',
    'cal.location': 'Location',
    'cal.color': 'Color',
    'cal.save': 'Save',
    'cal.cancel': 'Cancel',
    'cal.delete': 'Delete',
    'cal.noEvents': 'No events',
    // AI
    'ai.title': '✦ AI Assistant',
    'ai.greeting': 'Hello',
    'ai.greetingText': "I'm LifeSync AI — your personal assistant. I can help with planning, finance analysis and schedule optimization. How can I help?",
    'ai.placeholder': 'Type a message…',
    'ai.send': 'Send',
    'ai.suggestions': 'Quick Actions',
    'ai.q1': 'How much did I spend this week?',
    'ai.q2': 'What priority tasks are due tomorrow?',
    'ai.q3': 'Optimize my schedule for today',
    'ai.q4': 'Show habit report for the month',
    'ai.insights': '📊 AI Insights',
    'ai.startAdding': 'Start adding data',
    'ai.insightsHint': 'AI analytics will be available after filling in tasks and finances',
    // Settings
    'set.title': '⚙️ Settings',
    'set.profile': 'Profile',
    'set.appearance': 'Appearance',
    'set.currencies': 'Currencies',
    'set.integrations': 'Integrations',
    'set.account': 'Account',
    'set.language': 'Interface Language',
    'set.nickname': 'Name / Nickname',
    'set.nickPlaceholder': 'Enter your name',
    'set.email': 'Account email',
    'set.authMethod': 'Auth method',
    'set.baseCurrency': 'Base interface currency',
    'set.theme': 'Theme',
    'set.dark': '🌙 Dark',
    'set.light': '☀️ Light',
    'set.accent': 'Accent color',
    'set.rateInfo': 'Exchange rate to UAH for auto-conversion in the Finance section.',
    'set.monobank': 'Monobank API',
    'set.monoDesc': 'Auto-import transactions',
    'set.monoToken': 'API Token',
    'set.monoPlaceholder': 'Paste token from api.monobank.ua',
    'set.monoTest': 'Test',
    'set.monoGetToken': 'Get personal token →',
    'set.connected': '● Connected',
    'set.notConnected': '○ Not connected',
    'set.google': 'Google Workspace',
    'set.googleDesc': 'Calendar · Drive · Docs · Gmail',
    'set.googleClientId': 'Google OAuth 2.0 Web Client ID',
    'set.googleConnect': 'Connect Google',
    'set.googleUpdate': '✓ Connected (Update)',
    'set.googleNeedAuth': 'Authorization required',
    'set.googleSynced': 'Account synced',
    'set.changePassword': 'Change password',
    'set.exportData': 'Export data (JSON)',
    'set.logout': 'Log out',
    'set.deleteAccount': 'Delete account and clear storage',
    'set.deleteConfirm': 'Are you sure you want to delete your account and all associated data? This action cannot be undone.',
    'set.save': 'Save',
    'set.saved': '✓ Saved',
    'set.cancel': 'Cancel',
    'set.syncStatus': 'Sync status',
    'set.newPassword': 'New password',
    'set.confirmPassword': 'Confirm password',
    'set.savePassword': 'Save password',
    'set.passwordTitle': 'Change Password',
    'set.emailPassword': 'Email & Password',
    // TaskEditModal
    'edit.title': '✏️ Edit Task',
    'edit.taskName': 'Task name',
    'edit.taskPlaceholder': 'Task name…',
    'edit.priority': 'Priority',
    'edit.high': 'High',
    'edit.medium': 'Medium',
    'edit.low': 'Low',
    'edit.tagCategory': 'Tag / Category',
    'edit.tagPlaceholder': 'Dev, Business…',
    'edit.deadline': 'Deadline',
    'edit.status': 'Status',
    'edit.open': '○ Open',
    'edit.completed': '✓ Completed',
    'edit.delete': '🗑 Delete',
    'edit.cancel': 'Cancel',
    'edit.save': 'Save',
    // Common
    'common.close': 'Close',
    'common.more': 'More',
  },
};

interface LanguageCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const Ctx = createContext<LanguageCtx>({} as LanguageCtx);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('lifesync_lang');
    return (saved === 'en' || saved === 'uk') ? saved : 'uk';
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem('lifesync_lang', l);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] || translations['uk'][key] || key;
  }, [lang]);

  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export const useLanguage = () => useContext(Ctx);
